import type { CurriculumCourse } from "../schema";

type FlexCourse = CurriculumCourse<
  "flex-v1",
  "css.flex.axes",
  "flex-rules-v1"
>;

export const FLEX_COURSE: FlexCourse =
  Object.freeze<FlexCourse>({
  id: "flex-v1",
  version: 1,
  conceptId: "css.flex.axes-and-gap",
  skillId: "css.flex.axes",
  evaluatorId: "flex-rules-v1",
  title: "Flex 的两条轴怎么配合？",
  outcome: "能区分 gap、主轴对齐和交叉轴对齐，并在新结构中组合使用。",
  prerequisiteConceptIds: ["css.display", "css.declaration", "css.length.px"],
  behaviors: [
    {
      id: "flex.predict.gap",
      kind: "prediction",
      studentAction: "预测 gap 是否改变项目自身尺寸",
      observable: "结构化预测",
      successCriterion: "指出 gap 只增加相邻项目之间的间隔",
      independent: true,
    },
    {
      id: "flex.operate.axes",
      kind: "operation",
      studentAction: "分别保存 gap、justify-content、align-items 三次变化",
      observable: "三个不同不可变修订和 computed style",
      successCriterion: "依次达到 32px、center、flex-end",
      independent: true,
    },
    {
      id: "flex.explain.axes",
      kind: "explanation",
      studentAction: "说明主轴和交叉轴控制彼此独立",
      observable: "结构化解释及错误重试",
      successCriterion: "正确区分 gap、justify-content 与 align-items",
      independent: true,
    },
    {
      id: "flex.transfer.toolbar",
      kind: "transfer",
      studentAction: "在结构不同的工具栏写出四条 Flex 声明",
      observable: "学生原始 CSS 和真实布局测量",
      successCriterion: "flex、24px、space-between、center 同时成立",
      independent: true,
    },
  ],
  misconceptions: [
    {
      id: "flex.axes-swapped",
      label: "混淆主轴与交叉轴",
      conceptTags: ["main-vs-cross-axis", "justify-vs-align"],
      elicitationPrompt: "默认横向排列中，要让项目上下靠底，应改哪一个属性？",
      evidenceSignals: ["operation.justify-for-cross-axis", "explanation.axes-coupled"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "先确定 flex-direction，再沿主轴和交叉轴分别观察。",
      correctionQuestion: "默认横向 Flex 中，哪条属性控制上下对齐？",
      correctionCriterion: "选择 align-items 并指出它控制交叉轴",
    },
    {
      id: "flex.gap-resizes-items",
      label: "认为 gap 会改变项目自身尺寸",
      conceptTags: ["gap-vs-margin"],
      elicitationPrompt: "项目宽高不变时，增大 gap 会改项目本身还是项目之间？",
      evidenceSignals: ["prediction.gap-resizes", "explanation.gap-is-padding"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "分别量项目矩形和两个相邻项目之间的空白。",
      correctionQuestion: "项目宽高不变时，gap 增加的是哪一段空间？",
      correctionCriterion: "指出只增加相邻项目之间的间隔",
    },
    {
      id: "flex.item-owns-container-rules",
      label: "把容器属性写到子项目上",
      conceptTags: ["container-vs-item"],
      elicitationPrompt: "控制整排项目排列的 display:flex 应写在容器还是子项目？",
      evidenceSignals: ["operation.flex-on-item", "transfer.container-rule-on-child"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "先选中包住整排项目的共同父元素，再看它的计算样式。",
      correctionQuestion: "gap、justify-content、align-items 的共同作用对象是谁？",
      correctionCriterion: "指出三者写在 Flex 容器上，作用于其直接子项目的布局",
    },
    {
      id: "flex.margin-equals-gap",
      label: "认为每个子项的 margin 与容器 gap 完全等价",
      conceptTags: ["gap-vs-margin"],
      elicitationPrompt: "换行后仍要统一行列间距，应优先给容器 gap 还是逐项 margin？",
      evidenceSignals: ["operation.item-margin-for-gap", "explanation.gap-equals-outer-margin"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "观察首尾外侧是否也出现空白，并比较换行后的行间距。",
      correctionQuestion: "哪个属性只描述 Flex 项目之间的行列间隔？",
      correctionCriterion: "选择容器 gap，并说明它不等于每个项目的外边距",
    },
    {
      id: "flex.wrap-assumed",
      label: "认为空间不足时默认自动换行",
      conceptTags: ["wrap"],
      elicitationPrompt: "容器变窄但未设置 flex-wrap 时，项目会默认换到下一行吗？",
      evidenceSignals: ["prediction.default-wrap", "explanation.wrap-without-rule"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "读取 flex-wrap 的计算值，再缩窄容器观察。",
      correctionQuestion: "要允许多行排列，需要明确写出哪条声明？",
      correctionCriterion: "回答 flex-wrap: wrap，并指出默认值是 nowrap",
    },
    {
      id: "flex.direction-keeps-axis",
      label: "改变排列方向后仍沿用原来的主轴判断",
      conceptTags: ["direction", "main-vs-cross-axis", "justify-vs-align"],
      elicitationPrompt: "flex-direction 改成 column 后，justify-content 控制上下还是左右？",
      evidenceSignals: ["operation.column-justify-horizontal", "explanation.axis-ignores-direction"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "把主轴箭头随 flex-direction 一起旋转，再判断 justify。",
      correctionQuestion: "column 中主轴朝哪里，justify-content 因而控制哪一方向？",
      correctionCriterion: "回答主轴纵向，justify-content 控制上下分布",
    },
  ],
  hints: [
    {
      level: 1,
      text: "先判断当前主轴方向，再分别观察左右和上下哪一组发生变化。",
      revealsAnswer: false,
      creditEligibleAfterUse: true,
    },
    {
      level: 2,
      text: "gap 看项目之间；justify-content 看主轴；align-items 看交叉轴。",
      revealsAnswer: false,
      creditEligibleAfterUse: true,
    },
    {
      level: 3,
      text: "演示：display:flex; gap:24px; justify-content:space-between; align-items:center。",
      revealsAnswer: true,
      creditEligibleAfterUse: false,
    },
  ],
  factSources: [
    {
      id: "flex.fact.rects",
      kind: "browser-measurement",
      requiredFields: ["containerRect", "childRects", "itemMargins", "revisionId"],
    },
    {
      id: "flex.fact.computed",
      kind: "computed-style",
      requiredFields: ["display", "gap", "justifyContent", "alignItems", "flexDirection", "flexWrap"],
    },
    {
      id: "flex.fact.rule",
      kind: "matched-css-rule",
      requiredFields: ["selector", "property", "value", "source"],
    },
  ],
  transfer: {
    sourceStructure: ".demo-row/three-cards/flex",
    targetStructure: ".toolbar/actions-and-profile/flex",
    differences: ["dom", "rules", "visual"],
    hiddenItemIds: ["flex-transfer-b-1", "flex-transfer-b-2"],
  },
  accessibility: {
    regionLabel: "Flex 与定位小课",
    operationLabel: "Flex 样式控制器",
    transferInputLabel: "补写 Flex CSS 声明",
  },
  });
