import type { CurriculumCourse } from "../schema";

type PositioningCourse = CurriculumCourse<
  "positioning-v1",
  "css.positioning.flow",
  "positioning-rules-v1"
>;

export const POSITIONING_COURSE: PositioningCourse =
  Object.freeze<PositioningCourse>({
  id: "positioning-v1",
  version: 1,
  conceptId: "css.positioning.flow-and-containing-block",
  skillId: "css.positioning.flow",
  evaluatorId: "positioning-rules-v1",
  title: "元素为什么会离开队伍？",
  outcome: "能比较 static、relative、absolute 的占位与定位参照，并迁移到新结构。",
  prerequisiteConceptIds: ["css.normal-flow", "css.declaration", "css.length.px"],
  behaviors: [
    {
      id: "position.predict.flow",
      kind: "prediction",
      studentAction: "预测哪一种定位会离开普通文档流",
      observable: "结构化预测",
      successCriterion: "选择 absolute，并保留对 relative 占位的区分",
      independent: true,
    },
    {
      id: "position.operate.modes",
      kind: "operation",
      studentAction: "分别保存 static、relative、absolute 的 top 实验",
      observable: "三个分支修订、元素矩形和相邻元素位置",
      successCriterion: "保存 40px、40px、48px，且测量占位差异",
      independent: true,
    },
    {
      id: "position.explain.reference",
      kind: "explanation",
      studentAction: "解释 absolute 的脱流和最近定位祖先",
      observable: "结构化解释及重试次数",
      successCriterion: "同时指出脱流与 containing block",
      independent: true,
    },
    {
      id: "position.transfer.badge",
      kind: "transfer",
      studentAction: "在新海报结构中定位角标",
      observable: "学生原始 CSS、角标和祖先矩形",
      successCriterion: "absolute，距已定位祖先 top/right 各 16px",
      independent: true,
    },
  ],
  misconceptions: [
    {
      id: "position.relative-leaves-flow",
      label: "认为 relative 会释放原来的位置",
      conceptTags: ["document-flow", "relative-vs-absolute"],
      elicitationPrompt: "relative 元素偏移后，后面的元素会补进它原来的位置吗？",
      evidenceSignals: ["prediction.relative-leaves-flow", "explanation.relative-leaves-flow"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "同时标记元素显示位置与原来占位，观察后一个元素是否移动。",
      correctionQuestion: "relative 元素偏移后，后面的元素会不会占进它原来的位置？",
      correctionCriterion: "回答不会，并指出原位置仍被保留",
    },
    {
      id: "position.absolute-viewport",
      label: "认为 absolute 永远相对浏览器窗口",
      conceptTags: ["containing-block", "offset-reference"],
      elicitationPrompt: "absolute 的 top 从窗口量，还是从最近的已定位祖先量？",
      evidenceSignals: ["explanation.viewport-always", "transfer.offset-from-viewport"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "从目标向上找第一个 position 不是 static 的祖先。",
      correctionQuestion: "离角标最近、position 不是 static 的祖先是谁？",
      correctionCriterion: "能找到最近定位祖先并以它为参照",
    },
    {
      id: "position.static-offsets-move",
      label: "认为 static 元素会响应 top 或 left",
      conceptTags: ["static", "offset-reference"],
      elicitationPrompt: "保持 position:static，只写 top:40px，元素会移动吗？",
      evidenceSignals: ["prediction.static-top-moves", "operation.static-offset-no-effect-unexplained"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "先核对 position 的计算值，再观察 top 是否参与布局。",
      correctionQuestion: "top 要生效，position 至少需要不再是什么值？",
      correctionCriterion: "回答不能是 static，并能举出 relative 或 absolute",
    },
    {
      id: "position.absolute-keeps-space",
      label: "认为 absolute 仍在普通文档流中保留原占位",
      conceptTags: ["document-flow", "relative-vs-absolute"],
      elicitationPrompt: "元素改成 absolute 后，后面的元素会不会占进它原来的位置？",
      evidenceSignals: ["prediction.absolute-keeps-space", "explanation.absolute-in-flow"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "对比相邻元素在切换 absolute 前后的矩形位置。",
      correctionQuestion: "哪种定位会让元素离开普通文档流并释放原占位？",
      correctionCriterion: "回答 absolute，并与 relative 保留占位区分",
    },
    {
      id: "position.conflicting-insets",
      label: "忽略同时设置相对两侧偏移时的约束冲突",
      conceptTags: ["offset-conflict", "containing-block"],
      elicitationPrompt: "已有固定宽度时同时写 left 和 right，浏览器需要如何解决约束？",
      evidenceSignals: ["operation.left-right-fixed-width", "explanation.all-insets-always-apply"],
      minimumOccurrences: 2,
      singleErrorState: "uncertain",
      supportHint: "先列出包含块宽度、左右偏移、宽度和方向，再读取最终矩形。",
      correctionQuestion: "固定宽度的绝对定位元素同时有 left 与 right 时，能否只靠直觉断言最终位置？",
      correctionCriterion: "回答不能，应结合书写方向和计算结果核对被采用或忽略的约束",
    },
  ],
  hints: [
    {
      level: 1,
      text: "先看元素移动后，后面的元素有没有占进它原来的位置。",
      revealsAnswer: false,
      creditEligibleAfterUse: true,
    },
    {
      level: 2,
      text: "再从元素向上找，直到遇到第一个 position 不是 static 的祖先。",
      revealsAnswer: false,
      creditEligibleAfterUse: true,
    },
    {
      level: 3,
      text: "演示：父元素设 relative，角标设 absolute; top:16px; right:16px。",
      revealsAnswer: true,
      creditEligibleAfterUse: false,
    },
  ],
  factSources: [
    {
      id: "position.fact.rects",
      kind: "browser-measurement",
      requiredFields: ["targetRect", "ancestorRect", "siblingRects", "revisionId"],
    },
    {
      id: "position.fact.computed",
      kind: "computed-style",
      requiredFields: ["position", "top", "right", "bottom", "left", "width", "direction"],
    },
    {
      id: "position.fact.source",
      kind: "source-location",
      requiredFields: ["file", "line", "selector", "declaration"],
    },
  ],
  transfer: {
    sourceStructure: ".position-lab/three-branches/cards",
    targetStructure: ".poster/figure-and-badge",
    differences: ["dom", "rules", "visual"],
    hiddenItemIds: ["positioning-transfer-b-1", "positioning-transfer-b-2"],
  },
  accessibility: {
    regionLabel: "Flex 与定位小课",
    operationLabel: "定位偏移控制器",
    transferInputLabel: "补写定位 CSS 声明",
  },
  });
