export const foundationStatus = {
  phase: "P8",
  phaseLabel: "P8 · 三场景验收",
  nextPhase: "Competition readiness",
  enabledCapabilities: [
    "workspace",
    "strict-typescript",
    "testing",
    "database-schema",
    "teaching-canvas",
    "typed-block-shells",
    "local-canvas-recovery",
    "visibility-detection",
    "static-html-css-import",
    "sandboxed-runtime",
    "versioned-runtime-bridge",
    "immutable-import-snapshots",
    "element-selection",
    "box-model-inspection",
    "computed-style-inspection",
    "matched-rule-sources",
    "css-controls",
    "comparison-versions",
    "realtime-ai",
    "voice",
    "realtime-dynamic-tools",
    "text-question-fallback",
    "postgresql-authoritative-persistence",
    "offline-learning-outbox",
    "versioned-learning-evidence",
    "learning-proof-replay",
  ],
  deferredCapabilities: [
    "recoverable-session-deletion",
    "multi-device-sync",
    "deployment",
  ],
} as const;
